#define VIDEO_MOV @"video"
#define USERNAME @"username"
#define PASSWORD @"password"
#define TAG_VIEW_LOADING 100
#define TAG_VIEW_CAMERA 200
#define TAG_VIEW_BUILD_AVATAR 300
#define TAG_VIEW_DIALOG 400
#define TAG_VIEW_INSTALL_FIRMWARE 500
#define TIME_ANIMATION 0.3
#define DECIMAL_DIGIT 2
#define TAG_VIEW_CONTAIN 10
#define TAG_VIEW_ROTATE 100
#define TAG_IMAGE_ITEM 1000

#define ISSC_SERVICE_UUID      0xfff0
#define ISSC_CHAR_RX_UUID      0xfff7
#define ISSC_CHAR_TX_UUID      0xfff6
#define ISSC_SERVICE_UUID_NEW  0xffe0
#define ISSC_CHAR_RX_UUID_NEW  0xffe7
#define ISSC_CHAR_TX_UUID_NEW  0xffe6
#define SYSTEM_VERSION_LESS_THAN(v) ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedAscending)
enum BAND_DATA{
    BAND_DISCONNECT,
    BAND_DATA_POWERED,
    BAND_DATA_GET_DEVICES,
    BAND_CONNECTING,
    BAND_CONNECTED,
    
    STATE_POWERED_ON,
    STATE_POWERED_OFF,
    
    BAND_DATA_CHANGE_NEW_NAME,
    BAND_DATA_GET_GOAL,
    BAND_DATA_RESET_BAND,
    BAND_DATA_SET_CURRENT_TIME,
    BAND_DATA_SET_TIME_TYPE,
    BAND_DATA_SET_STRIDE_LENGTH,
    BAND_DATA_SET_STEP,
    BAND_DATA_START_REAL_TIME,
    BAND_DATA_STOP_REAL_TIME,
    BAND_DATA_SET_ALARM,
    BAND_DATA_ACTIVITY_DETAIL,
    BAND_DATA_TOTAL_ACTIVITY,
    BAND_DATA_DELETE_ACTIVITY,
    BAND_DATA_ZERO_NAME,
    BAND_DATA_HEART_RATE_MEASURING,
    BAND_DATA_MAC_ADDRESS,
    
    BAND_GET_GOAL_A,
    BAND_SET_NAME_A,
    BAND_RESET_A,
    BAND_TIME_MODE_A,
    BAND_CURRENT_TIME_A,
    BAND_STEPS_A,
    BAND_PERSONAL_INFOR_A,
    BAND_ACTIVITY_DETAIL_A,
    BAND_TOTAL_ACTIVITY_A,
    BAND_START_REAL_TIME_A,
    BAND_STOP_REAL_TIME_A,
    
    BAND_ENABLE_PASSWORD_C,
    BAND_GENERATE_NONCE_C,
    BAND_ID_DEVICE_C,
    BAND_DEVICE_TIME_C,
    BAND_ECDSA_VERIFICATION_C,
    BAND_ECDSA_VERIFICATION_C_FORMULA,
    BAND_PASSWORD_VERIFICATION_C,
    BAND_MAC_ADDRESS_C,
    BAND_FIRMWARE_VERSION_C,
    BAND_SET_DEVICE_NAME_C,
    BAND_CURRENT_TIME_C,
    BAND_GET_GOAL_C,
    BAND_SET_PERSONAL_INFOR_C,
    BAND_GET_PERSONAL_INFOR_C,
    BAND_TOTAL_DATA_C,
    BAND_TIME_MODE_C,
    BAND_START_REAL_TIME_C,
    BAND_STOP_REAL_TIME_C,
    BAND_SET_BASIC_PARAMATER_C,
    BAND_GET_BASIC_PARAMATER_C,
    BAND_GET_ACTIVITY_HISTORY_C,
    BAND_GET_HEART_RATE_HISTORY_C,
    BAND_MODE_C,
    BAND_ACTIVE_HEART_RATE_C,
    BAND_INSTALL_FIRMWARE_C
};
